services:
  x402-app:
    image: hashwarlock/x402-api:v0.0.12
    container_name: x402-app
    restart: unless-stopped
    environment:
      - DSTACK_SECRET_SALT=${DSTACK_SECRET_SALT}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4021:4021"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock

